# Installing NumPy

In [2]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


# How to import NumPy

In [3]:
import numpy as np

# Creating NumPy Arrays

## 1. Converting Python Sequence to NumPy Arrays

In [25]:
a1D = np.array([1, 2, 3, 4]) # np.array() is a function not a method.
a2D = np.array([[1, 2], [3, 4]])
a1D, a2D

(array([1, 2, 3, 4]),
 array([[1, 2],
        [3, 4]]))

### Array Attributes

In [33]:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int8)
arr.shape, a1D.shape

((2, 3), (4,))

In [28]:
arr.ndim

2

In [30]:
arr.size

6

In [34]:
arr.dtype

dtype('int8')

In [35]:
arr.itemsize

1

## 2. Intrinsic NumPy array creation functions

In [37]:
# 1D, 2D, nD
# 1D
a2 = np.arange(2, 4, 0.1) # start, stop, and step
b2 = np.arange(10)
a2, b2

(array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2,
        3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [38]:
a3 = np.linspace(1, 10, 9)
a3

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [42]:
# 2D
a4 = np.eye(3, 2, k=0)
a4

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [45]:
a5 = np.diag([[1, 0, 0], [0, 2, 0], [0, 0, 3]], k=-1)
a5

array([0, 0])

In [48]:
# nD
a6 = np.zeros((2, 3, 2))
a6

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [49]:
a7 = np.ones((2, 3, 2))
a7

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

# Indexing and slicing

In [54]:
a8 = np.array([10, 20, 30, 40, 50])
a8[0], a8[4], a8[-1], a8[-2]

(np.int64(10), np.int64(50), np.int64(50), np.int64(40))

In [60]:
a9 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a9[0, 0], a9[0][0], a9[2, 1]

(np.int64(1), np.int64(1), np.int64(8))

In [59]:
l1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
l1[0][0]

1

In [65]:
# slicing
# array[start:stop:step]
a10 = np.array([10, 20, 30, 40, 50])
a10[1:4:1], a10[:3], a10[2:], a10[::2]

(array([20, 30, 40]),
 array([10, 20, 30]),
 array([30, 40, 50]),
 array([10, 30, 50]))

In [66]:
a11 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a11[:2, 1:]

array([[2, 3],
       [5, 6]])

# Advanced Indexing

In [67]:
a12 = np.array([10, 20, 30, 40, 50])
indices = [0, 2]
a12[indices]

array([10, 30])

In [68]:
a13 =  np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows = [0, 1, 2]
cols = [1, 2, 0]
a13[rows, cols]

array([2, 6, 7])

In [73]:
a14 = np.array([10, 20, 30, 40, 50])
a14[a14 > 25], a14[[False, False, True, True, True]]

(array([30, 40, 50]), array([30, 40, 50]))

In [75]:
a15 = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
a15[indices][a15[indices] > 25]

array([30, 50])

# Element-wise Operations

In [82]:
# Arithmetic Operations
a16 = np.array([1, 2, 3])
a17 = np.array([4])
a16 + a17, a16 - a17, a16 * a17, a16 / a17

(array([5, 6, 7]),
 array([-3, -2, -1]),
 array([ 4,  8, 12]),
 array([0.25, 0.5 , 0.75]))

In [84]:
# Comparison Operations
a18 = np.array([1, 2, 3])
a19 = np.array([4, 5, 6])
a18 > a19, a18 < a19, a18 == a19

(array([False, False, False]),
 array([ True,  True,  True]),
 array([False, False, False]))

In [85]:
# Logical Operations
a20 = np.array([True, False, True])
a21 = np.array([False, True, True])
np.logical_and(a20, a21), np.logical_or(a20, a21), np.logical_not(a20)

(array([False, False,  True]),
 array([ True,  True,  True]),
 array([False,  True, False]))

In [86]:
# Trigonometric Operations
angles = np.array([0, np.pi/2, np.pi])
np.sin(angles), np.cos(angles), np.tan(angles)

(array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16]),
 array([ 1.000000e+00,  6.123234e-17, -1.000000e+00]),
 array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16]))

In [87]:
# Exponential and logarithmic Operations
a22 = np.array([1, 2, 3])
np.exp(a22), np.log(a22), np.log10(a22)

(array([ 2.71828183,  7.3890561 , 20.08553692]),
 array([0.        , 0.69314718, 1.09861229]),
 array([0.        , 0.30103   , 0.47712125]))

In [88]:
# Power and Modulus
a23 = np.array([2, 3, 4])
a24 = np.array([1, 2, 3])
a23 ** a24, a23 % a24

(array([ 2,  9, 64]), array([0, 1, 1]))

# Broadcasting

In [91]:
a25 = np.array([1, 2, 3])
n1 = 3
# a25 * n1
l1 = [1, 2, 3]
[i * n1 for i in l1]

[3, 6, 9]

In [93]:
shape1 = (2, 7, 1, 3)
shape2 = (5, 3)
arr1 = np.ones(shape1)
arr2 = np.ones(shape2)

result = arr1 + arr2
result.shape

(2, 7, 5, 3)

# Advanced Array Manipultions

In [96]:
# Reshaping Arrays
a26 = np.array([1, 2, 3, 4, 5, 6])
a26.reshape(-1, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [102]:
# Stacking Arrays
a27 = np.array([1, 2])
a28 = np.array([3, 4])
np.hstack((a27, a28)), np.vstack((a27, a28))

(array([1, 2, 3, 4]),
 array([[1, 2],
        [3, 4]]))

In [104]:
# Splitting Arrays
a29 = np.array([1, 2, 3, 4, 5, 6])
np.split(a29, 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [112]:
a30 = np.array([[1, 2, 3], [4, 5, 6]])
np.hsplit(a30, 3), np.vsplit(a30, 2)

([array([[1],
         [4]]),
  array([[2],
         [5]]),
  array([[3],
         [6]])],
 [array([[1, 2, 3]]), array([[4, 5, 6]])])

# Copies and Views

In [113]:
# view
a31 = np.arange(10)
b31 = a31[2:5]
b31[0] = 10
b31, a31

(array([10,  3,  4]), array([ 0,  1, 10,  3,  4,  5,  6,  7,  8,  9]))

In [114]:
# copy
a32 = np.arange(1, 10).reshape(3, 3)
b32 = a32[[0, 2]]
b32[0, 0] = 10
b32, a32

(array([[10,  2,  3],
        [ 7,  8,  9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

# Structured Arrays

In [121]:
dtype = np.dtype([
    ('name', 'U20'),
    ('age', np.int32),
    ('weight', np.float64)
])
data = np.array([
    ('Alice', 25, 65.2),
    ('Bob', 38, 72.9),
    ('Charlie', 35, 68.5)
], dtype=dtype)

data

array([('Alice', 25, 65.2), ('Bob', 38, 72.9), ('Charlie', 35, 68.5)],
      dtype=[('name', '<U20'), ('age', '<i4'), ('weight', '<f8')])

In [122]:
# data[0]
# data[0]['name']
# avg_age = np.mean(data['age'])
# avg_age
sorted_data = np.sort(data, order='age')
sorted_data

array([('Alice', 25, 65.2), ('Charlie', 35, 68.5), ('Bob', 38, 72.9)],
      dtype=[('name', '<U20'), ('age', '<i4'), ('weight', '<f8')])

# Linear Algebra Operations

In [124]:
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
dot_product = np.dot(vector_a, vector_b)
dot_product, np.cross(vector_a, vector_b)

(np.int64(32), array([-3,  6, -3]))

In [125]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
np.transpose(matrix)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [127]:
from numpy.linalg import det, inv
matrix2 = np.array([[1, 2], [3, 4]])
det(matrix2), inv(matrix2)

(np.float64(-2.0000000000000004),
 array([[-2. ,  1. ],
        [ 1.5, -0.5]]))

In [128]:
from numpy.linalg import eig
matrix3 = np.array([[2, 1], [1, 2]])
eigenValues, eigenVectors = eig(matrix3)
eigenValues, eigenVectors

(array([3., 1.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

# Random Number Generation

In [131]:
np.random.rand(), np.random.rand(3), np.random.rand(2, 3)

(0.6501515611399109,
 array([0.63420413, 0.95112249, 0.08238223]),
 array([[0.68301829, 0.56553217, 0.21741767],
        [0.71008195, 0.84152404, 0.33564198]]))

In [133]:
np.random.randint(1, 10), np.random.randint(1, 10, size=(2, 3))

(8,
 array([[2, 6, 8],
        [7, 8, 3]], dtype=int32))

In [134]:
list1 = [10, 20, 30, 40, 50]
np.random.choice(list1), np.random.choice(list1, size=3)

(np.int64(40), array([30, 30, 20]))

In [138]:
a33 = np.array([1, 2, 3, 4, 5])
# np.random.shuffle(a33)
# a33
np.random.permutation(a33), a33

(array([3, 1, 4, 5, 2]), array([1, 2, 3, 4, 5]))

# Questions

## Q1. Write a function that:
 1. Creates a 3x3 NumPy array with random integers between 1 and 20.
 2. Replaces all even numbers in the array with -1.
 3. Returns the modified array.

## Q2. Given two NumPy arrays, perform the following:
 1. Multiply their corresponding elements.
 2. Add 5 to each element of the result.
 3. Return the final array.

## Q3. Write a function that:
 1. Takes a 4x4 NumPy array as input.
 2. Extracts the second and third rows.
 3. Computes the sum of each column in the sliced array.
 4. Returns the result as a 1D array.

## Q4. Write a function that:
 1. Generates 15 random numbers from a uniform distribution between 0 and 1.
 2. Reshapes them into a 3x5 array.
 3. Normalizes the array so that its maximum value becomes 1 and its minimum value becomes 0.
 4. Returns the normalized array.

## Q5. Create a function that:
 1. Generates a 6x6 NumPy array with random integers between 10 and 50.
 2. Extracts all elements that are divisible by 5.
 3. Replaces these elements with 100.
 4. Returns the modified array and the extracted elements.

In [147]:
# sol 1
def replace_evens():
    arr = np.random.randint(1, 21, size=(3, 3))
    print("Original Array: ", arr)
    arr[arr % 2 == 0] = -1
    return arr

replace_evens()

Original Array:  [[19  6 12]
 [ 4  3 13]
 [11  8  6]]


array([[19, -1, -1],
       [-1,  3, 13],
       [11, -1, -1]], dtype=int32)

In [148]:
# sol 2
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 * arr2
result += 5
result

array([ 9, 15, 23])

In [149]:
# sol 3
def slice_and_analyze(arr):
    sliced_arr = arr[1:3, :]
    col_sum = np.sum(sliced_arr, axis=0)
    return col_sum

arr3 = np.random.randint(1, 21, size=(4, 4))
arr3, slice_and_analyze(arr3)

(array([[15, 12, 18, 11],
        [12,  1, 11, 15],
        [12,  3,  2, 16],
        [13, 19, 14,  5]], dtype=int32),
 array([24,  4, 13, 31]))

In [150]:
# sol 4
def normalized_random_array():
    arr = np.random.rand(15)
    print("Original array: ", arr)
    arr = arr.reshape(3, 5)
    arr_min = np.min(arr)
    arr_max = np.max(arr)
    normalized_arr = (arr - arr_min) / (arr_max - arr_min)
    return normalized_arr

normalized_random_array()

Original array:  [0.41868153 0.46552533 0.02893849 0.63046217 0.68165774 0.50009793
 0.81487008 0.17048216 0.31047655 0.38956653 0.84198787 0.96608177
 0.4695759  0.50670213 0.08645886]


array([[0.41588415, 0.46586989, 0.        , 0.64186949, 0.69649888],
       [0.50276137, 0.83864614, 0.15103738, 0.30042157, 0.38481633],
       [0.86758278, 1.        , 0.47019214, 0.50980853, 0.06137841]])

In [151]:
# sol 5
def advanced_indexing():
    arr = np.random.randint(10, 51, size=(6, 6))
    print("Original array: ", arr)
    divisible_by_5 = arr[arr % 5 == 0]
    arr[arr % 5 == 0] = 100
    return arr, divisible_by_5

advanced_indexing()

Original array:  [[42 35 14 25 12 32]
 [37 39 10 40 32 25]
 [16 14 46 11 39 14]
 [33 36 41 37 29 27]
 [45 30 24 32 47 45]
 [35 10 35 26 45 22]]


(array([[ 42, 100,  14, 100,  12,  32],
        [ 37,  39, 100, 100,  32, 100],
        [ 16,  14,  46,  11,  39,  14],
        [ 33,  36,  41,  37,  29,  27],
        [100, 100,  24,  32,  47, 100],
        [100, 100, 100,  26, 100,  22]], dtype=int32),
 array([35, 25, 10, 40, 25, 45, 30, 45, 35, 10, 35, 45], dtype=int32))